# replicaCount: 1

# image:
#   repository: zukien/product-service
#   tag: v1
#   pullPolicy: IfNotPresent

# service:
#   type: ClusterIP
#   port: 8080
#   targetPort: 8080

# config:
#   dbHost: postgres
#   dbPort: "5432"
#   springProfile: prod

# secret:
#   username: postgres
#   password: password

# resources: {}

# probes:
#   startup:
#     path: /actuator/health
#     initialDelaySeconds: 10
#     periodSeconds: 5
#     timeoutSeconds: 2
#     failureThreshold: 30

#   liveness:
#     path: /actuator/health/liveness
#     initialDelaySeconds: 30
#     periodSeconds: 10
#     timeoutSeconds: 2
#     failureThreshold: 3

#   readiness:
#     path: /actuator/health/readiness
#     initialDelaySeconds: 20
#     periodSeconds: 5
#     timeoutSeconds: 2
#     successThreshold: 1
#     failureThreshold: 3


image:
  repository: zukien/product-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: http

config:
  dbPort: "5432"

secret:
  username: postgres

probes:
  startup:
    path: /actuator/health
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30

  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
canary:
  enabled: false
  replicas: 1
  image:
    repository: zukien/product-service
    tag: ""

otel:
  serviceName: product-service
  endpoint: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
  protocol: grpc
