postgres:

  replicaCount: 1

  image:
    repository: postgres
    tag: "16"

  port: 5432

  database: productdb

  username: postgres

  password: passwords

  service:
    name: postgres
    type: ClusterIP