# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "product-service.fullname" . }}-config

# data:
#   SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.config.dbHost }}:{{ .Values.config.dbPort }}/productdb"
#   SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}