apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "product-service.fullname" . }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "product-service.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "product-service.name" . }}

    spec:
      containers:
        - name: product-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ include "product-service.fullname" . }}-config
            - secretRef:
                name: {{ include "product-service.fullname" . }}-secret

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          # startupProbe:
          #   httpGet:
          #     path: {{ .Values.probes.startup.path }}
          #     port: {{ .Values.service.targetPort }}
          #   initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          #   timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
          #   failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}