apiVersion: v1
kind: Secret

metadata:
  name: {{ include "product-service.fullname" . }}-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "passwords"