apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/version: 0.12.0
data:
  config.yaml: |-
    "resourceRules":
      "cpu":
        "containerLabel": "container"
        "containerQuery": |
          sum by (<<.GroupBy>>) (
            irate (
                container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!="",pod!=""}[4m]
            )
          )
        "nodeQuery": |
          sum by (<<.GroupBy>>) (
            irate(
                node_cpu_usage_seconds_total{<<.LabelMatchers>>}[4m]
            )
          )
        "resources":
          "overrides":
            "namespace":
              "resource": "namespace"
            "node":
              "resource": "node"
            "pod":
              "resource": "pod"

      "memory":
        "containerLabel": "container"
        "containerQuery": |
          sum by (<<.GroupBy>>) (
            container_memory_working_set_bytes{<<.LabelMatchers>>,container!="",pod!=""}
          )
        "nodeQuery": |
          sum by (<<.GroupBy>>) (
            node_memory_working_set_bytes{<<.LabelMatchers>>}
          )
        "resources":
          "overrides":
            "node":
              "resource": "node"
            "namespace":
              "resource": "namespace"
            "pod":
              "resource": "pod"

      "window": "5m"

    "rules":
      - "seriesQuery": 'http_server_requests_seconds_count{namespace="default",service="product-service",pod!=""}'
        "resources":
          "overrides":
            "namespace":
              "resource": "namespace"
            "pod":
              "resource": "pod"
        "name":
          "matches": "http_server_requests_seconds_count"
          "as": "http_requests_per_second"
        "metricsQuery": |
          sum by (pod) (
            rate(
              http_server_requests_seconds_count{
                namespace="default",
                service="product-service",
                uri!="/actuator/health"
              }[2m]
            )
          )
