name: Ecom CI

on:
  push:
    branches:
      - main
      - testin

  pull_request:
    branches:
      - main

jobs:

  #################################################
  # Detect which services changed
  #################################################

  changes:

    name: Detect Changed Services
    runs-on: ubuntu-latest

    outputs:
      product: ${{ steps.filter.outputs.product }}
      inventory: ${{ steps.filter.outputs.inventory }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Detect Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            product:
              - 'product-service/**'

            inventory:
              - 'inventory-service/**'

            frontend:
              - 'frontend/**'


  #################################################
  # Product CI
  #################################################

  product:

    name: Product Service CI
    needs: changes

    if: needs.changes.outputs.product == 'true'

    uses: ./.github/workflows/product-ci.yml

    secrets: inherit


  #################################################
  # Inventory CI
  #################################################

  inventory:

    name: Inventory Service CI
    needs: changes

    if: needs.changes.outputs.inventory == 'true'

    uses: ./.github/workflows/inventory-ci.yml

    secrets: inherit


  #################################################
  # Frontend CI
  #################################################

  frontend:

    name: Frontend CI
    needs: changes

    if: needs.changes.outputs.frontend == 'true'

    uses: ./.github/workflows/frontend-ci.yml

    secrets: inherit


